[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
testnet    = "https://ethereum-sepolia-rpc.publicnode.com"
mainnet   = "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
